hpe-container-platform-community/hpecp-python-library

- hpecp/user.py
> Fixes hpe-container-platform-community/hpecp-python-library#8

- hpecp/client.py
- hpecp/user.py
Added user property to client; altered docstrings in user.
Fixes hpe-container-platform-community/hpecp-python-library#8
> Added user property to the client module. Altered docstr in user module

- bin/cli.py
> Added support for list option for k8sworker

- .vscode/settings.json
> Enabled formatOnSave in settings

- hpecp/client.py
- hpecp/user.py
- tests/library/user_test.py
Hi ,
I created UserController to query for /ap/v1/user
I could see some tests are failing when using with tox command, but I dont see those are related to this change.
> Fix for issue #7, list users

- bin/cli.py
Fixes hpe-container-platform-community/hpecp-python-library#34
> Added method to retrieve the list of users

- .vscode/settings.json
- bin/cli.py
- hpecp/k8s_worker.py
- requirements.txt
Really nice @bharath-m-g, thanks!!
> Query filter

- .gitpod.Dockerfile
- DEVELOPING.md
- tests/HPECP-REST-API-SOAPUI.xml
> Add SOAP UI

- bin/cli.py
- hpecp/client.py
- hpecp/role.py
• role.py module implemented with get() method
• role() method added to client module
• RoleProxy() class implemented in cli module
> reformatted role.py

- bin/cli.py
- hpecp/catalog.py
- tests/library/catalog_test.py
> add catalog list() test

- .travis.yml
- bin/cli.py
> add flake8 build stage

- .travis.yml
- DEVELOPING.md
- tests/cli/cli_test.py
- tests/cli/k8s_cluster_test.py
- tests/library/client_test.py
- tests/library/config_test.py
- tests/library/gateway_test.py
- tests/library/k8s_cluster_test.py
- tests/library/k8s_worker_test.py
- tests/library/tenant_test.py
- tests/library/user_test.py
- tox.ini
> add -s to pytest

- .gitpod.yml
- .travis.yml
- hpecp/client.py
> add client.py docstring check

- .travis.yml
- hpecp/catalog.py
- hpecp/k8s_worker.py
- hpecp/license.py
- hpecp/lock.py
> add docstrings to catalog

- .gitpod.yml
- .vscode/settings.json
- Added 'Python Docstring Generator' extension to gitpod settings
Signed-off-by: Bharath Narayan <bharath.m-g@hpe.com>
> Setup 'numpy' as the default docstring format

- .travis.yml
- hpecp/gateway.py
- hpecp/k8s_cluster.py
- hpecp/license.py
- hpecp/user.py
> add hpecp/tenant doc check

- tests/cli/cli_test.py
> add test for missing config file

- DEVELOPING.md
- bin/cli.py
- tests/cli/cli_test.py
- tests/library/catalog_test.py
- tests/library/k8s_cluster_test.py
- tests/library/tenant_test.py
> add cli configure tests

- bin/cli.py
- hpecp/client.py
- setup.cfg
- tests/cli/cli_test.py
- tests/library/k8s_cluster_test.py
> fix more doc strings

- pre_push_verifications.sh
- tests/cli/cli_test.py
> test hpe_config_file env var is used

- tests/library/tenant_test.py
> reinstate skipped tests

- .github/workflows/build.yml
- .github/workflows/checks.yml
Signed-off-by: Bharath Narayan<bharath.m-g@hpe.com>
> Updated github workflow schedules/options

- bin/cli.py
- hpecp/client.py
- hpecp/gateway.py
- hpecp/k8s_worker.py
- tests/library/k8s_worker_test.py
Fixes #74
Signed-off-by: Bharath Narayan <bharath.m-g@hpe.com>
> Fixed `set_storage` on k8sworker

- .github/workflows/build.yml
- requirements.txt
- setup.py
> move build deps

- bin/cli.py
- hpecp/base_resource.py
- hpecp/catalog.py
- hpecp/k8s_cluster.py
- hpecp/k8s_worker.py
- tests/library/catalog_test.py
- tests/library/k8s_cluster_test.py
> start moving wait_for_status method

- hpecp/base_resource.py
- hpecp/gateway.py
- tests/library/gateway_test.py
> refactor gateway to use base class

- bin/cli.py
- tests/library/k8s_cluster_test.py
> more refactoring

- bin/cli.py
> move wait for status method

- tests/library/catalog_test.py
> add catalog attribute tests

- bin/cli.py
- tests/library/catalog_test.py
> add catalog cli get test

- tests/library/catalog_test.py
> add catalog get cli test

- bin/cli.py
- tests/library/base_test.py
- tests/library/catalog_test.py
- tests/library/cli_test.py
> print errors to stdout

- hpecp/gateway.py
> fix gateway list

- bin/cli.py
> revert cli method signature

- bin/cli.py
- tests/library/catalog_test.py
- tests/library/gateway_test.py
> delete catalog delete

- tests/library/gateway_test.py
> add cli test for wait for. status

- bin/cli.py
- tests/library/gateway_test.py
> test gateway wait cli - check stderr

- bin/cli.py
- tests/library/gateway_test.py
> remove method - use parent's instead

- bin/cli.py
- tests/library/catalog_test.py
> test catalog cli install

- bin/cli.py
- tests/library/catalog_test.py
- tests/library/gateway_test.py
> add gateway cli create tests

- bin/cli.py
- tests/library/gateway_test.py
> fix formatting

- bin/cli.py
- tests/library/gateway_test.py
> test gateway cli wait for delete

- bin/cli.py
- tests/library/base_test.py
- tests/library/gateway_test.py
- tests/library/k8s_worker_test.py
> add cli k8sworker tests

- bin/cli.py
- tests/library/k8s_worker_test.py
> cli k8s worker set storage tests

- bin/cli.py
- requirements.txt
- tests/library/cli_test.py
- tox.ini
> add autocomplete implementation

- bin/cli.py
- tests/library/cli_test.py
> disable test for py27

- bin/cli.py
> remove assertions from cli list method

- bin/cli.py
> remove assertions for cli list

- bin/cli.py
> remove assertions from cli

- bin/cli.py
> replace asserts with syserr

- bin/cli.py
- tests/library/base_test.py
- tests/library/lock_test.py
> add lock cli test

- bin/cli.py
- hpecp/lock.py
- pre_push_verifications.sh
- tests/library/lock_test.py
> add cli lock create test

- pre_push_verifications.sh
- tests/library/lock_test.py
> add lock create with exception test

- hpecp/k8s_worker.py
> comment out unimplemented method

- tests/library/k8s_worker_test.py
> test assertions

- .gitignore
- bin/cli.py
- tests/library/k8s_worker_test.py
> remove file lookup from cli autocomplete

- bin/cli.py
> add autocomplete for column names

- bin/cli.py
- requirements.txt
- tests/library/catalog_test.py
> add pydecor

- bin/cli.py
- requirements.txt
> switch to wrapt

- bin/cli.py
- tests/library/gateway_test.py
- tests/library/k8s_worker_test.py
> more @intercept_exception

- bin/cli.py
- tests/library/cli_test.py
> dont require config for autocompete output

- bin/cli.py
- tests/library/k8s_worker_test.py
> add k8sworker get test with setup_log

- hpecp/role.py
- hpecp/user.py
> remove redundant code

- bin/cli.py
> add TODO doc

- bin/cli.py
- hpecp/base_resource.py
- hpecp/k8s_cluster.py
- hpecp/k8s_worker.py
- tests/library/k8s_worker_test.py
> add setup_log

- tests/library/k8s_cluster_test.py
> add test for missing props

- hpecp/k8s_cluster.py
- tests/library/k8s_cluster_test.py
> add status_message test

- tests/library/gateway_test.py
> fix format

- hpecp/client.py
- tests/library/client_test.py
> more tests

- tests/library/k8s_cluster_test.py
> add cli create k8s cluster test

- bin/cli.py
- tests/library/k8s_cluster_test.py
> add more tests

- bin/cli.py
- tests/library/license_test.py
> add license tests

- bin/cli.py
- hpecp/client.py
- hpecp/gateway.py
- hpecp/k8s_cluster.py
- hpecp/k8s_worker.py
- hpecp/license.py
- hpecp/lock.py
- hpecp/tenant.py
- hpecp/user.py
- tests/library/base_test.py
- tests/library/license_test.py
> covert headers to CaseInsensitiveDict

- bin/cli.py
- tests/library/cli_test.py
> add http post and put tests

- bin/cli.py
> intercept_exception

- bin/cli.py
> fix logging

- bin/cli.py
- hpecp/base_resource.py
- hpecp/client.py
- hpecp/logger.py
- tests/library/cli_test.py
> refactor (broken)

- bin/cli.py
> improve autocomplete file/dir completions

- bin/cli.py
> Fixes #176

- bin/cli.py
- hpecp/tenant.py
- tests/library/tenant_test.py
> start refactoring

- bin/cli.py
> add tenant to cli

- bin/cli.py
> add tenant proxy to cli

- bin/cli.py
> add create method

- bin/cli.py
> add tenant.create()

- hpecp/tenant.py
> remove invalid field

- bin/cli.py
- tests/library/base_test.py
- tests/library/cli_test.py
> add test for profiles

- bin/cli.py
> get_addons method

- bin/cli.py
- hpecp/k8s_cluster.py
> add method get_available_addons

- hpecp/k8s_cluster.py
> fix lookup

- README.md
- hpecp/client.py
> add requests logging

- pre_push_verifications.sh
- tests/base_test.py
- tests/cli_test.py
- tests/k8s_cluster_mock_api.py
- tests/k8s_cluster_test.py
- tests/k8s_worker_test.py
> refactor k8s cluster tests

- Dockerfile
- pre_push_verifications.sh
- tests/base.py
- tests/base_test.py
- tests/catalog_mock_api_responses.py
- tests/catalog_test.py
- tests/cli_mock_api_responses.py
- tests/cli_test.py
- tests/client_mock_api_responses.py
- tests/client_test.py
- tests/config_mock_api_responses.py
- tests/config_test.py
- tests/gateway_mock_api_responses.py
- tests/gateway_test.py
- tests/k8s_cluster_mock_api_responses.py
- tests/k8s_cluster_test.py
- tests/k8s_worker_mock_api_responses.py
- tests/k8s_worker_test.py
- tests/license_mock_api_responses.py
- tests/license_test.py
- tests/lock_mock_api_responses.py
- tests/lock_test.py
- tests/role_mock_api_responses.py
- tests/role_test.py
- tests/tenant_mock_api_responses.py
- tests/tenant_test.py
- tests/user_mock_api_responses.py
- tests/user_test.py
> more test refactoring

- README.md
- hpecp/cli/k8scluster.py
- hpecp/k8s_cluster.py
> Example edit

- hpecp/cli/k8scluster.py
> add new method to __dir__

- hpecp/cli/k8scluster.py
- hpecp/k8s_cluster.py
> Fixes hpe-container-platform-community/hpecp-python-library#241

- hpecp/tenant.py
> fix(cli): #243

- bin/cli.py
- hpecp/cli/datatap.py
- hpecp/client.py
- hpecp/datatap.py
> add datatap functionality

- hpecp/cli/datatap.py
- hpecp/datatap.py
> add create to datatap

- hpecp/datatap.py
> fix(datatap): update list fields

- hpecp/datatap.py
> fix(datatap): add list columns

- hpecp/k8s_cluster.py
Signed-off-by: jear <jerome.armand@hpe.com>
> feat(import): import cluster with json

- hpecp/cli/k8scluster.py
- hpecp/k8s_cluster.py
- tests/_HPECP-REST-API-SOAPUI.xml
Signed-off-by: Erdinc Kaya <erdincka@msn.com>
> initial try
